### ISSUE TITLE
关于JUDGE文件权限问题

### ISSUE THREAD

**Issue by nlpCSir** [yuzhanglong/YuJudge-Core#4]
您好，请问您的server使用Judge服务时，是如何避免judge对输出重定向所在文件的访问权限问题的呢？

**Comment by yuzhanglong** [comment]
以管理员身份运行 judgeCore

**Comment by yuzhanglong** [comment]
如果你的意思是指安全沙箱机制 可以看看readme里面的文章

**Comment by nlpCSir** [comment]
请问沙箱里使用的是绝对文件路径还是相对呢？


在 2022-11-14 13:13:55，"怀策策" ***@***.***> 写道：

如果你的意思是指安全沙箱机制 可以看看readme里面的文章

**Comment by yuzhanglong** [comment]
> 请问沙箱里使用的是绝对文件路径还是相对呢？ 在 2022-11-14 13:13:55，"怀策策" ***@***.***> 写道： 如果你的意思是指安全沙箱机制 可以看看readme里面的文章 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

相对路径应该也可以，但强烈建议使用绝对路径。
@nlpCSir

**Comment by nlpCSir** [comment]
谢谢！



在 2022-11-17 15:05:49，"怀策策" ***@***.***> 写道：

请问沙箱里使用的是绝对文件路径还是相对呢？ 在 2022-11-14 13:13:55，"怀策策" @.> 写道： 如果你的意思是指安全沙箱机制 可以看看readme里面的文章 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>

相对路径应该也可以，但强烈建议使用绝对路径。
