### ISSUE TITLE
about ru_maxrss

### ISSUE THREAD

**Issue by nlpCSir** [yuzhanglong/YuJudge-Core#5]
我用ru_maxrss统计资源占用时，发现仅运行main{return 0;}的代码段就需要2400多kb的占用。并且我在代码中加入了一个长度为1000的int数组，ru_maxrss并未按我设想的增加4kb。所以我有以下问题
1、ru_maxrss的单位是什么？
2、在子进程execve前的操作会不会影响父进程统计的ru_maxrss大小呢？
3、为什么我增加1000的int数组，ru_maxrss并未增加4的整数倍呢？

十分感谢您的代码，受益良多，希望您能指教

**Comment by yuzhanglong** [comment]
1. 对于问题1，可以去 manual docs 里面搜索相关的结构体，我搜索到的结果如下：
https://man7.org/linux/man-pages/man2/getrusage.2.html
<img width="858" alt="image" src="https://user-images.githubusercontent.com/56540811/206471397-e33eb538-5b1b-4c41-b1ea-aa289aa34423.png">
提示：在 Mac 系统下单位又有所不同，建议在 Linux 下搞。
2. 不会，ru_maxrss 是 wait4 调用后的结果，和之前的代码没关系。
3. 肯定不会，这个影响因素太多了，你的编译器版本、采用了相关编译优化、声明这个 int 数组在代码中的占用情况、占用了多少、当前操作系统的状态都有可能影响最终可执行文件的内存消耗，会和你计算的有一些误差。时间也是类似的道理。你可能会有疑问，这个不是测不准了吗？实际上卡时间或者卡内存是卡一个比较大的区间范围，足以决定算法优劣，例如某个算法有 O(n) 和 O(n2) 的解法，那么肯定能卡住 O(n2)，反之，如果某个算法的多种方案复杂度十分接近，例如 O(n) 和 O(2n)，那么也没必要卡。

**Comment by nlpCSir** [comment]
十分感谢您的回答，但是我还是有些不解，我多次访问judge的时候，内存占用在持续增多，请问您是否知晓可能的原因呢？并且我只运行main(){return 0;}的代码段就得到了2300多kb的占用，这应该是不合理的吧

**Comment by yuzhanglong** [comment]
> 十分感谢您的回答，但是我还是有些不解，我多次访问judge的时候，内存占用在持续增多，请问您是否知晓可能的原因呢？并且我只运行main(){return 0;}的代码段就得到了2300多kb的占用，这应该是不合理的吧

第一个问题：你的样本可能太少了，你跑个一千次肯定不会一直增加，而是在一个大致的范围内。
第二个问题：很合理，机器面向的是可执行文件，不是你给的那两行代码，类似的，如果你用 Python、Java、JavaScript 这种解释性语言，消耗内存、时间可能会更多。

**Comment by nlpCSir** [comment]
第一个样本排除了样本少的可能，是持续增多，每访问三次，就会增加4kb

**Comment by nlpCSir** [comment]
并且虽然如您所说，我们只是限制比较大的范围，可是如果我们没法将初始的内存获取到，又怎么去限制用户设定的空间复杂度呢

**Comment by yuzhanglong** [comment]
> 第一个样本排除了样本少的可能，是持续增多，每访问三次，就会增加4kb

不清楚，我从来没复现过。

**Comment by yuzhanglong** [comment]
> 并且虽然如您所说，我们只是限制比较大的范围，可是如果我们没法将初始的内存获取到，又怎么去限制用户设定的空间复杂度呢

需要出题人在平台上按照不同的写法自行测试，确保卡住（你总不能不测试就拿出来给别人做吧？）。本来时间和内存就不是从 0 开始的，也不需要获取所谓初始内存。

**Comment by yuzhanglong** [comment]
> > 并且虽然如您所说，我们只是限制比较大的范围，可是如果我们没法将初始的内存获取到，又怎么去限制用户设定的空间复杂度呢
> 
> 需要出题人在平台上按照不同的写法自行测试，确保卡住（你总不能不测试就拿出来给别人做吧？）。本来时间和内存就不是从 0 开始的，也不需要获取所谓初始内存。

 你也可以去问问你出过算法题的竞赛朋友们，问问他们是怎么出题的，怎么在 OnlineJudge 平台上卡时间的

**Comment by yuzhanglong** [comment]
这个”初始“内存的概念就没有意义，我们判题核心只面向可执行文件。

**Comment by yuzhanglong** [comment]
而且不同编程语言的内存也是不一样的，所以不同语言他们的时间、内存复杂度也是要分开讨论的，这个你在其他的oj平台上也看的出来

**Comment by yuzhanglong** [comment]
所以出题人出题应该是理论和实践相结合的，不是你手算一个时间复杂度以后就是这样的结果，还要结合你的平台去调试（上面说过，根据编译器、runtime 的不同时间、空间消耗也是会有区别）。

**Comment by yuzhanglong** [comment]
方便的话可以给本项目一个 star 哈
